djangotweet/djangotweet/urls.py
from django.contrib import admin
from django.urls import path,include

urlpatterns = [
    path("admin/", admin.site.urls),
    path("",include('tweetapp.urls')),  #içine tweetapp/ yazmassak ana sayfada gider artık 
                                        #tweetapp/ eklememize gerek kalmaz
    path("",include('django.contrib.auth.urls'))
]                                       

djangotweet/tweetapp/urls.py
from django.urls import path
from . import views

app_name = 'tweetapp'

urlpatterns = [
    path('',views.listtweet,name='listtweet'), #siteadı/tweetapp/
    #burda tweetapp e girildiğinde ilk açılacak sayfayı listtweet olarak seçtik
    path('addtweet/',views.addtweet,name='addtweet'),     #siteadı/tweetapp/apptweet 
    path('addtweetbyform',views.addtweetbyform,name='addtweetbyform'), #siteadı/tweetapp/addtweetbyform
    path('addtweetbymodelform',views.addtweetbymodelform,name='addtweetbymodelform'),#siteadı/tweetapp/addtweetbymodelform
    path('signup/',views.SignUpView.as_view(),name="signup"),  #SignUpView.as_view() şeklinde görünüre çeviririz class olduğu için   
    path("deletetweet/<int:id>",views.deletetweet,name="deletetweet"), # silme id siyle beraber aldık 
] 

djangotweet/tweetapp/models.py
from django.db import models
from django.contrib.auth.models import User # burada kullanıcın username e ulaşmak için

# Create your models here.

class Tweet(models.Model):
    #nickname = models.CharField(max_length=50) uygulamada kayıt olduktan sonra artık user name girmeye gerek yok kayıt olma işlemini ekledikten sonra bu kısmı kaldırdık
    username = models.ForeignKey(User,on_delete=models.CASCADE,null=True) #burada foreignkey ile user modeline eriştik ondelete ise kullanıcı silinirse tweetlere nolacak karar verir silinir yaptık ve sonradan eklediğimiz için null ekledik önceki kullanıcılara boşluk ataması için başta eklesek gerek olmazdı
    message = models.CharField(max_length=100)

    def __str__(self):
        return f"Tweet user: {self.username} message: {self.message}"
        #return f"Tweet nick: {self.nickname} message: {self.message}" nickname varken ki hali

djangotweet/tweetapp/forms.py
from django import forms
from django.forms import ModelForm #3.kullanım formda
from tweetapp.models import Tweet

class AddTweetForm(forms.Form): #2.yöntem 
    nickname_input = forms.CharField(label="Nickname",max_length=50)
    message_input = forms.CharField(label="Message",max_length=100,
                                    widget=forms.Textarea(attrs={"class":"tweetmessage"}))
    
class AddTweetModelForm(ModelForm): #3.yöntem
    class Meta:
        model = Tweet
        fields = ["username","message"]  #modelde koyduğumuz yerler eskinden username yazan yerlerde nickname yazıyodu

djangotweet/tweetapp/views.py
from django.shortcuts import render,redirect
from . import models
from django.urls import reverse,reverse_lazy #reverse den farkı sadece buraya ulaşıldığında çalışır reverse her uygulama başladğında çalışır buda sadece kayıt olmasına rağmen her seferinde çalışması gereken birşey değil
from tweetapp.forms import AddTweetForm,AddTweetModelForm #django form kısmı için ve modelform için
from django.contrib.auth.decorators import login_required
from django.contrib.auth.forms import UserCreationForm #kullanıcı oluşturma formu
from django.views.generic import CreateView # buda üsttekini kullanabilmek için

# Create your views here.

def listtweet(request):
    all_tweets = models.Tweet.objects.all()
    tweet_dict = {"tweets":all_tweets}
    return render(request, 'tweetapp/listtweet.html',context=tweet_dict)

@login_required(login_url="/login")
def addtweet(request):
    if request.POST: #request postsa çalışacak kısım 
        #nickname = request.POST["nickname"] #buranın içindeki yazılar html de  artık ihtiyacımız yok
        message = request.POST["message"]  #name olarak eklediğimiz yerlerin ismi
        #tweet = models.Tweet(nickname,message)
        #tweet.save()    #db e kaydettik
        models.Tweet.objects.create(username=request.user,message=message) #nickname=nickname vardı önceden
        #şeklinde de kaydedebiliriz db e
        return redirect(reverse('tweetapp:listtweet'))   #diğer html e yönlendirdik gönderince
    else: #burası getle çalıştığından else yazsak olur
        return render(request, 'tweetapp/addtweet.html')
    

def addtweetbyform(request):  #djangonun otomatik formlarıyla yaptık html kodu çok az yazdık 2.form yoludur
    if request.method == "POST":#üsttekinin 2.türü
        form = AddTweetForm(request.POST)
        if form.is_valid():  #form geçerli değerler aldıysa demek
            nickname = form.cleaned_data["nickname_input"] #forms.py de giriş yapılan alanların ismi
            message = form.cleaned_data["message_input"]#yani alınan değerleri yine html e yönlendirdik
            models.Tweet.objects.create(nickname=nickname,message=message) #models deki veri tabanına kaydettik
            return redirect(reverse('tweetapp:listtweet')) #button tıklanınca ana sayfaya yönlendirdik
        else:
            print("error in form!") #olurda form hatalı çalışırsa 
            return render(request,'tweetapp/addtweetbyform.html',context={"form":form})
    else:
        form = AddTweetForm()
        return render(request,'tweetapp/addtweetbyform.html',context={"form":form})
    

def addtweetbymodelform(request): #3.form yoludur
    if request.method == "POST": #üstten kopyaladık
        form = AddTweetModelForm(request.POST)
        if form.is_valid():  
            nickname = form.cleaned_data["nickname"] #forms.py de bu şekilde kayıtlı
            message = form.cleaned_data["message"]
            models.Tweet.objects.create(nickname=nickname,message=message) 
            return redirect(reverse('tweetapp:listtweet')) 
        else:
            print("error in form!") 
            return render(request,'tweetapp/addtweetbymodelform.html',context={"form":form})
    else:
        form = AddTweetModelForm()
        return render(request,'tweetapp/addtweetbymodelform.html',context={"form":form})
    
@login_required
def deletetweet(request,id):  #tweet silme özelliği
    tweet = models.Tweet.objects.get(pk=id) #güncel tweet i aldık
    if request.user == tweet.username:   # güvenlik önlemi için bu request i yapan kullanıcı tweet in kullanıcısa eşit sil işlemini yaptık
        models.Tweet.objects.filter(id=id).delete()  #burada tweet.delete() de yapabilirdik
        return redirect('tweetapp:listtweet')  # sildikten sonra sayfa yönlendirmesi

class SignUpView(CreateView):
    form_class = UserCreationForm  #burası birebir olmalı hangi formu kullanacağımız
    success_url = reverse_lazy("login")  #başarılı olursa nereye yönlendirileceği
    template_name = "registration/signup.html"  #hangi templete bağlı olduğunu belirttik tweetapp de yapabilirdik

djangotweet/templates/base.html
{% load static %}
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-T3c6CoIi6uLrA9TneNEoa7RxnatzjcDSCmG1MXxSR1GAsXEV/Dwwykc2MPK8M2HN" crossorigin="anonymous">
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-C6RzsynM9kWDrMNeT87bh95OGNyZPhcTNXj1NW7RuBCsyN/o0jlpcV8Qyq46cDfL" crossorigin="anonymous"></script>
    <title>Tweet App</title>
    <link rel="stylesheet" href="{% static 'tweetapp/customform.css' %}">
</head>
<body class="mainpage">
    <nav class="navbar navbar-expand-md navbar-dark bg-dark mb-4">
        <div class="container-fluid" style="background-color: #1A8DDA;">
          <a class="navbar-brand" href="{%url 'tweetapp:listtweet'%}">Tweet App</a>
          <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarCollapse" aria-controls="navbarCollapse" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
          </button>
          <div class="collapse navbar-collapse" id="navbarCollapse">
            <ul class="navbar-nav me-auto mb-2 mb-md-0">
              <li class="nav-item">
                <a class="nav-link active" aria-current="page" href="{% url 'tweetapp:listtweet' %}">List</a>
              </li>
              <li class="nav-item">
                <a class="nav-link" href="{% url 'tweetapp:addtweet' %}">Add Tweet</a>
              </li>
              <!-- buraları diğer yöntemleri görmek için yapmıştık
              <li class="nav-item">
                <a class="nav-link" href="{% url 'tweetapp:addtweetbyform' %}">Add Tweet By Form</a>
              </li>
              <li class="nav-item">
                <a class="nav-link" href="{% url 'tweetapp:addtweetbymodelform' %}">Add Tweet By Model Form</a>
              </li>
              -->
              {% if not user.is_authenticated %} <!--burda eğer giriş yapmadıysa gösterir-->
              <li class="nav-item">
                <a class="nav-link" href="{% url 'login' %}">Login</a>  <!--bunu tweet app içine koymadık direk projenin kendisine koyduğumuzdan app içinde vermeyiz-->
              </li>
              {%else%}    <!--giriş yaptıysa gösterir-->
              <li class="nav-item">
                <a class="nav-link" href="{% url 'logout' %}?next=/">Logout</a> <!--bu login logout oto oluşturulmuş şeyler urls eklediğimiz şey sayesinde ve ?next=/ bu ibare çıkış yaptıktan sonra nereye yönelendirileceğini belirttik ana sayfaya-->
              </li>
              {% endif %}
              <li class="nav-item">
                <a class="nav-link" href="{% url 'tweetapp:signup' %}">Signup</a>
              </li>
            </ul>
          </div>
        </div>
      </nav>


    {% block content %}

    {%endblock%}

</body>
</html>

djangotweet/tweetapp/templates/tweetapp/addtweet.html
{% extends "base.html" %}

{%block content%}
<form action="" method="POST">  
    {% csrf_token %}  <!--güvenlik ihlalinin önlemek için-->
    <!--burda post kullanırız çünkü get genelde bilgi alınırken post yollarken kullanırız-->
    <div class="container" style="width: 50%;">
    <!--
      <div class="mb-3">
      <label for="nickname" class="form-label">Nickname</label>
      <input type="text" class="form-control" id="nickname" name="nickname">
    </div>
    -->
    <div class="mb-3">
      <label for="message" class="form-label" style="color: white;">Message</label>
      <input type="text" class="form-control" id="message" name="message">
    </div>
    <button type="submit" class="btn btn-primary" style="background-color: #1A8DDA;">Send Tweet</button>
  </div>
  </form>
{%endblock%}

djangotweet/tweetapp/templates/tweetapp/addtweetbyform.html
{% extends "base.html" %}
{% load static %}


{%block content%}
<h1>AddTweetByForm Page</h1>
<div class="container tweetform">
  <form action="" method="POST">  
      {% csrf_token %}  

        {%for field in form%}
      <div class ="mb-3">
        {{field.label_tag}}
        {{field}}
      </div>
        {%endfor%}
      
    <button type="submit" class="btn btn-primary">Send Tweet</button>
    </form>
</div>
{%endblock%}

<!--<div class="mb-3">  biz ekledik normal formda butonun altta olması için yapılmış class tı
  {{form.as_p}}  <paragraf olarak göster ekledik as_p  normalde böyle yaptık ama düzenleme özelleştirme için yukarıda ekledik
</div>-->

djangotweet/tweetapp/templates/tweetapp/addtweetbymodelform.html
{% extends "base.html" %}
{% load static %}


{%block content%}
<h1>AddTweetByModelForm Page</h1>
<div class="container tweetform">
    <form action="" method="POST">  
        {% csrf_token %}  
  
          {%for field in form%}
        <div class ="mb-3">
          {{field.label_tag}}
          {{field}}
        </div>
          {%endfor%}
        
      <button type="submit" class="btn btn-primary">Send Tweet</button>
      </form>
  </div>
{%endblock%}

djangotweet/tweetapp/templates/tweetapp/listtweet.html
{% extends "base.html" %}

{%block content%}


<div class="container" style="width: 50%;">
    {%for tweet in tweets%}
        <div class="card" style="padding: 10px; background-color: black;">
            <div class="card-header" style="background-color: #1A8DDA;">
                <h4>{{tweet.username}}</h4> <!--nickname yazıyodu eskiden-->
            </div>
            <div class="card-body">
                <p class="card-text" style="color: white;">{{tweet.message}}</p>
            </div>
            {%if tweet.username == user%}  <!--burda dediğimiz kullanıcı güncel kullanıcıya eşitse çalışır yani kendi tweetini silebilir ancak-->
            <a href="{% url 'tweetapp:deletetweet' id=tweet.id %}" class="btn btn-danger" style="width: 150px;">Delete Tweet</a>
            {%endif%}
        </div>    
    {%endfor%}
</div>

{%endblock%}



<!-- block ların içinde
<h1>ListTweet Page</h1>
<ul>
    {%for tweet in tweets%}
        <li><h2></h2>{{tweet.nickname}} = {{tweet.message}}</h2></li>
        {%endfor%}
    </ul>
normal hali buydu düzenleme frontend eklemek için-->  